### ISSUE TITLE
Licence not specified

### ISSUE THREAD

**Issue by lighterowl** [retrodaredevil/io-lib#2]
I couldn't find a file specifying the licence of this project : would you be kind enough to specify it by adding a `LICENCE` file to the main directory and appropriate file headers?

Thanks!

**Comment by retrodaredevil** [comment]
https://github.com/retrodaredevil/io-lib/commit/be7cb21c931759d7555839b0daffbf0bd39614ab fixes this. Let me know if you have any questions.

Thanks
